import { Architects_Daughter } from "next/font/google";
import "./globals.css";

const architectsDaughter = Architects_Daughter({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-body",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${architectsDaughter.variable} antialiased font-handwriting`}
      >
        {children}
      </body>
    </html>
  );
}
