import { 
  siGithub,  
  siGoogle, 
  siReact, 
  siTypescript,
  siNodedotjs,
  siVuedotjs,
  siDocker,
  siDiscord,
  siSlack,
  siSpotify,
  siTailwindcss,
  siFigma,
  siUnity,
  siPython,
  siSharp,
  siHtml5,
  siCss,
  siFlutter,
  siJavascript,
  siDjango,
  siRuby,
  siCloudflare,
  siDotnet,
  siNextdotjs,
  siLua,
  siRos,
  siReplit,
  siLaravel,
  siEclipseide,
  siNginx,
  siNpm,
  siPhp,
  siPrisma,
  siPycharm,
  siVercel,
  siMongodb,
  siJira,
} from 'simple-icons';

export const iconMap = {
  github: siGithub,
  google: siGoogle,
  react: siReact,
  typescript: siTypescript,
  nodejs: siNodedotjs,
  vue: siVuedotjs,
  docker: siDocker,
  discord: siDiscord,
  slack: siSlack,
  spotify: siSpotify,
  tailwind: siTailwindcss,
  figma: siFigma,
  unity: siUnity,
  python: siPython,
  csharp: siSharp,
  html: siHtml5,
  css: siCss,
  flutter: siFlutter,
  javascript: siJavascript,
  django: siDjango,
  ruby: siRuby,
  cloudflare: siCloudflare,
  dotnet: siDotnet,
  nextjs: siNextdotjs,
  lua: siLua,
  ros: siRos,
  replit: siReplit,
  laravel: siLaravel,
  eclipse: siEclipseide,
  nginx: siNginx,
  npm: siNpm,
  php: siPhp,
  prisma: siPrisma,
  pycharm: siPycharm,
  vercel: siVercel,
  mongodb: siMongodb,
  jira: siJira,
} as const;

export type IconName = keyof typeof iconMap;
